### ISSUE TITLE
Question: What is the "small ROM"?

### ISSUE THREAD

**Issue by TheTechRobo** [isotherm/betawise#8]
From https://github.com/isotherm/betawise/wiki/Research-Information#reset-information

**Comment by isotherm** [comment]
The small ROM is similar to a bootloader. It runs a minimal version of OS3K and (in essence) only accepts firmware updates or applet operations. Using the key sequence, you can enter that mode before the main ROM takes over. If you are using AlphaSmart Manager or [neotools](https://github.com/lykahb/neotools) you should then be able to load firmware and applets in that mode.

It is stored in a separate area of flash from the main ROM, the idea being to provide a fallback in case a ROM upgrade fails. However, it's protected no differently than the main ROM. The file is `smallos3kneorom.os3kos`, but I would not recommend trying to update the small ROM for the above reasons.
