### ISSUE TITLE
Neo Manager no longer available

### ISSUE THREAD

**Issue by chrisbrandow** [isotherm/betawise#9]
I'm not sure if there's another way to install applets without it.

**Comment by isotherm** [comment]
https://github.com/lykahb/neotools can install applets and is my recommendation for everyone if you are comfortable with the command line... However, when the memory fills up, you have to erase the ROM and then manually reinstall all of the applets you want.

If any of that sounds scary, then maybe you want to still try Manager. For now, Neo Manager is available via the Internet Archive:
* PC: https://web.archive.org/web/20211126072647/http://support.renlearn.com/techkb/download/NEOManager3_9_3USPC.zip
* Mac: https://web.archive.org/web/20211126063257/https://support.renlearn.com/techkb/download/NEOManager3_9_3USMac.zip

**Comment by TheTechRobo** [comment]
Neotools (https://github.com/lykahb/neotools) might work but that's Linux/Mac only.

Edit: Ninja'd lol

**Comment by isotherm** [comment]
> but that's Linux/Mac only.

I think it can work on Windows too... Or at least, there's libusb for Windows. I'm pretty sure I've used `neotools` on Windows before.

**Comment by TheTechRobo** [comment]
Ah I just got confused since the instructions are for linux and mac only.

**Comment by chrisbrandow** [comment]
thanks. I'll try Neotools. sorry I overlooked that.

FWIW, as you likely know, neomanager is 32-bit only, so can't run on any new Macs.
